Use MySQL 5.x
MySQL v8 causes error:
```
[Nest] 1622   - 2/7/2019, 10:48:13 AM   [ExceptionHandler] Client does not support authentication protocol requested by server; consider upgrading MySQL client +40ms
SequelizeConnectionError: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Utils.Promise.tap.then.catch.err (/home/mchelen/doc/code/nest/sample/07-sequelize/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)
```